version: '3.7'
services:
  web:
    container_name: 'flask_api'
    build: ./api
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development
    depends_on:
      - prometheus
  prometheus:
    container_name: 'prometheus'
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./alert_rules.yaml:/etc/prometheus/alert_rules.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
    depends_on:
      - alertmanager
  
  grafana:
    container_name: 'grafana'
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - '3278:3000'
  
  alertmanager:
    container_name: 'alertmanager'
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yaml/:/etc/alertmanager/alertmanager.yaml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'
      - '--storage.path=/alertmanager'

volumes:
  prometheus_data: {}
  grafana_data: {}
