version: '3.7'
services:
  web:
    container_name: 'flask_api'
    build: ./api
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    environment:
      FLASK_ENV: 'development'

  prometheus:
    container_name: 'prometheus'
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
  
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - '3278:3278'

volumes:
  prometheus_data: {}
  grafana_data: {}
