apiVersion: v1
kind: Pod
metadata:
  name: redis-client
  namespace: redis
spec:
  restartPolicy: Always
  containers:
  - name: redis-client
    image: docker.io/bitnami/redis:7.4.1-debian-12-r2
    command:
    - sleep
    - infinity
    resources:
      limits:
        cpu: 100m
        memory: 128Mi